### ISSUE TITLE
Code and version requirements broken with Terraform v0.15

### ISSUE THREAD

**Issue by jtgorny** [terraform-aws-modules/terraform-aws-key-pair#20]
## Description
Receiving an error with the deprecated `list` function when upgrading to Terraform binary v0.15

## Versions
Terraform v0.15.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.7.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0

## Reproduction
terraform init
terraform plan

### Code Snippet to Reproduce
```
Error: Error in function call
│ 
│   on .terraform/modules/test_ssh_keypair.tls_private_key/outputs.tf line 2, in output "algorithm":
│    2:   value = concat(tls_private_key.key.*.algorithm, list(""))[0]
│ 
│ Call to function "list" failed: the "list" function was deprecated in Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax to write a literal list.

 Error: Error in function call
│ 
│   on .terraform/modules/tls_private_key/outputs.tf line 2, in output "algorithm":
│    2:   value = concat(tls_private_key.key.*.algorithm, list(""))[0]
│ 
│ Call to function "list" failed: the "list" function was deprecated in Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax to write a literal list.
```

## Additional context
The error is replicated a number of times in both the real and the test modules

**Comment by jtgorny** [comment]
I suspect it could be a hashicorp/tls v3.1.0 compatibility issue but posting here for visibility.

**Comment by antonbabenko** [comment]
Make sure that you are using `v0.6.0` of this module. Your version does not support Terraform 0.15.
