### ISSUE TITLE
No provider "aws" plugins meet the constraint

### ISSUE THREAD

**Issue by franviera92** [terraform-aws-modules/terraform-aws-key-pair#3]
Hello!

I have problem with new update

> fran@fran-X580VD:~/mesa-dinero/dev/back$ terraform init
> Initializing modules...
> Downloading terraform-aws-modules/key-pair/aws 0.3.0 for key_pair2...
> - key_pair2 in .terraform/modules/key_pair2/terraform-aws-modules-terraform-aws-key-pair-06fa6de
> 
> Initializing the backend...
> 
> Initializing provider plugins...
> - Checking for available provider plugins...
> 
> No provider "aws" plugins meet the constraint "~> 2.23,~> 2.46.0,~> 2.53".
> 
> The version constraint is derived from the "version" argument within the
> provider "aws" block in configuration. Child modules may also apply
> provider version constraints. To view the provider versions requested by each
> module in the current configuration, run "terraform providers".
> 
> To proceed, the version constraints for this provider must be relaxed by
> either adjusting or removing the "version" argument in the provider blocks
> throughout the configuration.
> 
> 
> Error: no suitable version is available

**Comment by antonbabenko** [comment]
Hi @franviera92 !

You need to update your installed Terraform AWS provider. The simplest way is to remove `.terraform` directory and run `terraform init` once more.

If for some reason you have to use the previous version, then you have to use the previous version of this module.

**Comment by wsizoo** [comment]
Make sure you don't have a `provider_override.tf` file with a version set.

**Comment by queglay** [comment]
I am also seeing this when I try to use aws provider version 3.0.0 with terraform 0.12.29
I attempted to remove the .terraform folder but the problem remained.

https://github.com/terraform-providers/terraform-provider-aws/issues/14443
